from .anasayfa import anasayfa
from .iletisim import İletisimFormView
from .kategori import KategoriListView
from .yazilarim import yazilarim
from .detay import DetayView
from .yazi_ekle import YaziEkleCreateView
from .yazi_guncelle import YaziGuncelleUpdateView
from .yazi_sil import YaziSilDeleteView
from .yorum_sil import yorum_sil